# Site Settings
title: Wu Research Group
description: 
url: "https://wuroy.github.io"
baseurl: ""

# Author
author:
  name: Guangqi Wu
  email: guangqiwu@outlook.com
  bio: "About me"
  hero_bio: "I'm currently an incoming professor at  postdoctoral fellow in the Department of Chemistry at the University of Oxford, where I work with Prof. Hagan Bayley and Prof. Yujia Qing on sequencing synthetic polymers using protein nanopores. I received my Ph.D. in polymer chemistry and physics from Peking University in 2020 under Prof. Hua Lu, focusing on polypeptide synthesis via ring-opening polymerization of N-carboxyanhydrides. I then stayed on for a two-year postdoc in the same group, before moving to the Massachusetts Institute of Technology to join Prof. Connor Coley’s group, where I developed automation and machine-learning tools to accelerate the discovery of synthetic polymers."
  avatar: /assets/images/avatar.jpg

# Social Links
social:
  github: https://github.com/wuRoy
  linkedin: https://www.linkedin.com/in/guangqi-wu-a31b02239
  email: guangqiwu@outlook.com
  google_scholar: https://scholar.google.com/citations?user=y7sRCX0AAAAJ&hl=en

# Build Settings
markdown: kramdown
highlighter: rouge
future: true

# Sass
sass:
  sass_dir: assets/css
  style: compressed

# Plugins
plugins:
  - jekyll-feed
  - jekyll-seo-tag
  - jekyll-sitemap

# Collections
collections:
  news:
    output: true
    permalink: /news/:title/
  people:
    sort_by: order

# Exclude
exclude:
  - Gemfile
  - Gemfile.lock
  - README.md
  - AGENTS.md
  - node_modules
  - vendor
